### ISSUE TITLE
Circular reveal fails on older devices (4.4.2)

### ISSUE THREAD

**Issue by behelit** [HarinTrivedi/FABRevealMenu-master#18]
`11-06 20:20:56.760 10561-10561/xxx.appname E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: xxx.appname, PID: 10561
                                                                        java.lang.NoSuchMethodError: io.codetail.animation.ViewAnimationUtils.createCircularReveal
                                                                            at com.hlab.fabrevealmenu.helper.AnimationHelper.startCircularRevealAnim(AnimationHelper.java:106)
                                                                            at com.hlab.fabrevealmenu.helper.AnimationHelper.revealMenu(AnimationHelper.java:69)
                                                                            at com.hlab.fabrevealmenu.view.FABRevealMenu$5.run(FABRevealMenu.java:311)
                                                                            at android.os.Handler.handleCallback(Handler.java:733)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:157)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5356)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                            at dalvik.system.NativeStart.main(Native Method)`

I think it's related to this:
https://github.com/ozodrukh/CircularReveal/issues/32

**Comment by HarinTrivedi** [comment]
Support has been removed for os <21
Sorry!!
